name: Node CI Demo
on:
    pull_request:
        branches: [master]
jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x, 14.x, 16.x]
        steps:
            - uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Cache Node.js module
              uses: actions/cache@v3
              with:
                    path: ~/.npm
                    key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-${{ matrix.node-version }}-
                        ${{ runner.os }}-node-
                        ${{ runner.os }}-
            - name: Run tests
              run: npm test