name: Node CI Demo
on:
    pull_request:
        branches: [master]
jobs:
    test_pull_request:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - run: npm ci
            - run: npm run test --if-present
            - run: npm run build --if-present
            